---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: python
    pdns_version: "{{ lookup('ansible.builtin.env', 'pdns_version') }}"
    common_args: &common
      api_key: foo
    d1_rrset: ["192.168.0.1"]
    d2_rrset: ["192.168.1.1", "192.168.1.2", "192.168.1.3"]
    d3t1_rrset: ["192.168.2.1"]
    d3t2_rrset: ["192.168.2.2", "192.168.2.3"]

  pre_tasks:
    - name: Creating zone with single rrset and single record
      kpfleming.powerdns_auth.zone:
        <<: *common
        name: d1.rrset-record.example.
        state: present
        properties:
          kind: Native
          nameservers:
            - ns.example.
          soa:
            mname: localhost.
            rname: hostmaster.localhost.
          rrsets:
            - name: t1.d1.rrset-record.example.
              type: A
              records: "{{ d1_rrset | map('dict_kv', 'content') | list }}"
      ignore_errors: true
      register: result_d1

    - name: Creating zone with single rrset and multiple records
      kpfleming.powerdns_auth.zone:
        <<: *common
        name: d2.rrset-record.example.
        state: present
        properties:
          kind: Native
          nameservers:
            - ns.example.
          soa:
            mname: localhost.
            rname: hostmaster.localhost.
          rrsets:
            - name: t1.d2.rrset-record.example.
              type: A
              records: "{{ d2_rrset | map('dict_kv', 'content') | list }}"
      ignore_errors: true
      register: result_d2

    - name: Creating zone with multiple rrsets
      kpfleming.powerdns_auth.zone:
        <<: *common
        name: d3.rrset-record.example.
        state: present
        properties:
          kind: Native
          nameservers:
            - ns.example.
          soa:
            mname: localhost.
            rname: hostmaster.localhost.
          rrsets:
            - name: t1.d3.rrset-record.example.
              type: A
              records: "{{ d3t1_rrset | map('dict_kv', 'content') | list }}"
            - name: t2.d3.rrset-record.example.
              type: A
              records: "{{ d3t2_rrset | map('dict_kv', 'content') | list }}"
      ignore_errors: true
      register: result_d3

    - ansible.builtin.assert:
        quiet: true
        that:
          - '"exception" not in item'
          - not item.failed
          - item.changed
      loop:
        - "{{ result_d1 }}"
        - "{{ result_d2 }}"
        - "{{ result_d3 }}"

    - ansible.builtin.assert:
        quiet: true
        that:
          - (item[1] | split(',') | sort) == item[0]
      loop:
        - "{{ d1 }}"
        - "{{ d2 }}"
        - "{{ d3t1 }}"
        - "{{ d3t2 }}"
      vars:
        d1_retrieved_rrset: "{{ lookup('dig_local', 't1.d1.rrset-record.example.', qtype='A', flat=1, fail_on_error=false, real_empty=false) }}"
        d2_retrieved_rrset: "{{ lookup('dig_local', 't1.d2.rrset-record.example.', qtype='A', flat=1, fail_on_error=false, real_empty=false) }}"
        d3t1_retrieved_rrset: "{{ lookup('dig_local', 't1.d3.rrset-record.example.', qtype='A', flat=1, fail_on_error=false, real_empty=false) }}"
        d3t2_retrieved_rrset: "{{ lookup('dig_local', 't2.d3.rrset-record.example.', qtype='A', flat=1, fail_on_error=false, real_empty=false) }}"
        d1:
          - "{{ d1_rrset }}"
          - "{{ d1_retrieved_rrset }}"
        d2:
          - "{{ d2_rrset }}"
          - "{{ d2_retrieved_rrset }}"
        d3t1:
          - "{{ d3t1_rrset }}"
          - "{{ d3t1_retrieved_rrset }}"
        d3t2:
          - "{{ d3t2_rrset }}"
          - "{{ d3t2_retrieved_rrset }}"

  tasks:
    - name: check adding rrset to existing zone
      kpfleming.powerdns_auth.zone:
        <<: *common
        name: d1.rrset-record.example.
        state: present
        properties:
          rrsets:
            - name: t2.d1.rrset-record.example.
              type: A
              changetype: REPLACE
              records:
                - content: 10.0.0.1
                - content: 10.0.0.2
      ignore_errors: true
      register: result

    - ansible.builtin.assert:
        quiet: true
        that:
          - '"exception" not in result'
          - not result.failed
          - result.changed
          - (d1t2_rrset | sort(attribute='address') | map(attribute='address' | list) == ["10.0.01", "10.0.0.2"]
          - (d1t2_rrset | sort(attribute='address') | map(attribute='type' | list) == ['A', 'A']
          - (d1t2_rrset | sort(attribute='address') | map(attribute='ttl' | list) == [3600, 3600]
      vars:
        d1t2_rrset: "{{ lookup('dig_local', 't2.d1.rrset-record.example.', qtype='A', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check replacing records on existing rrset in existing zone
      kpfleming.powerdns_auth.zone:
        <<: *common
        name: d1.rrset-record.example.
        state: present
        properties:
          rrsets:
            - name: t2.d1.rrset-record.example.
              type: A
              changetype: REPLACE
              records:
                - content: 172.16.0.1
      ignore_errors: true
      register: result

    - ansible.builtin.assert:
        quiet: true
        that:
          - '"exception" not in result'
          - not result.failed
          - result.changed
          - (d1t2_rrset | sort(attribute='address') | map(attribute='address' | list) == ["172.16.0.1"]
          - (d1t2_rrset | sort(attribute='address') | map(attribute='type' | list) == ['A']
          - (d1t2_rrset | sort(attribute='address') | map(attribute='ttl' | list) == [3600]
      vars:
        d1t2_rrset: "{{ lookup('dig_local', 't2.d1.rrset-record.example.', qtype='A', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check adding records on existing rrset in existing zone
      kpfleming.powerdns_auth.zone:
        <<: *common
        name: d1.rrset-record.example.
        state: present
        properties:
          rrsets:
            - name: t2.d1.rrset-record.example.
              type: A
              changetype: REPLACE
              keep: true
              records:
                - content: 172.16.0.2
      ignore_errors: true
      register: result

    - ansible.builtin.assert:
        quiet: true
        that:
          - '"exception" not in result'
          - not result.failed
          - result.changed
          - (d1t2_rrset | sort(attribute='address') | map(attribute='address') | list) == ["172.16.0.1", "172.16.0.2"]
          - (d1t2_rrset | sort(attribute='address') | map(attribute='type') | list) == ['A', 'A']
          - (d1t2_rrset | sort(attribute='address') | map(attribute='ttl') | list) == [3600, 3600]
      vars:
        d1t2_rrset: "{{ lookup('dig_local', 't2.d1.rrset-record.example.', qtype='A', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check removing rrset from existing zone
      kpfleming.powerdns_auth.zone:
        <<: *common
        name: d1.rrset-record.example.
        state: present
        properties:
          rrsets:
            - name: t1.d2.rrset-record.example.
              type: A
              changetype: DELETE
      ignore_errors: true
      register: result

    - ansible.builtin.assert:
        quiet: true
        that:
          - '"exception" not in result'
          - not result.failed
          - result.changed
          - d1t2_rrset == "NXDOMAIN"
      vars:
        d1t2_rrset: "{{ lookup('dig_local', 't1.d2.rrset-record.example.', qtype='A', flat=0, fail_on_error=false, real_empty=false) }}"
