- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: python
    common_args: &common
      api_key: foo
      zone_name: cryptokeys.example.

  pre_tasks:
    - name: Creating Native zone for cryptokeys tests
      kpfleming.powerdns_auth.zone:
        name: cryptokeys.example.
        api_key: foo
        state: present
        properties:
          kind: Native
          account: test-account1
          nameservers:
            - ns.example.
          soa:
            mname: localhost.
            rname: hostmaster.localhost.
        metadata:
          allow_axfr_from:
            - AUTO-NS
          ixfr: true
          axfr_source: 127.0.0.1
      register: result

    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is not defined
          - not result.failed
          - result.changed
          - result.zone.name == "cryptokeys.example."
          - result.zone.kind == "Native"
          - result.zone.account == "test-account1"
          - result.zone.metadata.allow_axfr_from[0] == "AUTO-NS"
          - result.zone.metadata.ixfr
          - result.zone.metadata.axfr_source == "127.0.0.1"

  tasks:
    - name: check that there are no keys
      kpfleming.powerdns_auth.cryptokey:
        <<: *common
        state: "exists"
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is not defined
          - not result.failed
          - result.cryptokey == {}
          - result.cryptokeys == []
          - output == ""
      vars:
        output: "{{ lookup('dig_local', 'cryptokeys.example.', qtype='DNSKEY', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check generated key creation
      kpfleming.powerdns_auth.cryptokey:
        <<: *common
        state: "present"
        cryptokey:
          keytype: csk
          algorithm: ed25519
          active: true
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] not defined
          - not result.failed
          - result.cryptokey.algorithm == "ed25519"
          - result.cryptokey.active == true
          - result.cryptokey.keytype == "csk"
          - output.algorithm == 15
          - output.owner == "cryptokeys.example."
      vars:
        output: "{{ lookup('dig_local', 'cryptokeys.example.', qtype='DNSKEY', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check key deletion
      kpfleming.powerdns_auth.cryptokey:
        <<: *common
        state: "absent"
        cryptokey_id: 1
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is not defined
          - not result.failed
          - result.cryptokey == {}
          - result.cryptokeys == []
          - output == ""
      vars:
        output: "{{ lookup('dig_local', 'cryptokeys.example.', qtype='DNSKEY', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check imported key creation
      kpfleming.powerdns_auth.cryptokey:
        <<: *common
        state: "present"
        cryptokey:
          keytype: zsk
          dnskey: "257 3 15 lMu/7quhLeSueMcdlt3T0sxln32yhrhASCKKDB1xJOk="
          privatekey: "Private-key-format: v1.2\nAlgorithm: 15 (ED25519)\nPrivateKey: Rnt2dv3mWMmP8bU/8koayZ4R5dWdI86zJmZ0nnjPe6Q=\n"
          active: true
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is not defined
          - not result.failed
          - result.cryptokey["algorithm"] == "ED25519"
          - result.cryptokey["active"] == true
          - result.cryptokey["keytype"] == "zsk"
          - result.cryptokey["dnskey"] == "257 3 15 lMu/7quhLeSueMcdlt3T0sxln32yhrhASCKKDB1xJOk="
          - (result.cryptokey["ds"] | length) > 0
          - output["key"] == "lMu/7quhLeSueMcdlt3T0sxln32yhrhASCKKDB1xJOk="
          - output["algorithm"] == 15
      vars:
        output: "{{ lookup('dig_local', 'cryptokeys.example.', qtype='DNSKEY', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check listing of all keys
      block:
        - kpfleming.powerdns_auth.cryptokey:
            <<: *common
            state: "present"
            cryptokey:
              keytype: ksk
              algorithm: ed25519
          register: cryptokey
        - kpfleming.powerdns_auth.cryptokey:
            <<: *common
            state: "exists"
          ignore_errors: true
          register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is not defined
          - not result.failed
          - (result.cryptokeys | length) == 2
          - result.cryptokey == {}
    - ansible.builtin.set_fact:
        last_id: "{{ cryptokey.cryptokey.id }}"

    - name: check activating key
      block:
        - kpfleming.powerdns_auth.cryptokey:
            <<: *common
            state: present
            cryptokey_id: "{{ last_id }}"
            cryptokey:
            active: true
          ignore_errors: true
          register: result_active
        - kpfleming.powerdns_auth.cryptokey:
            <<: *common
            state: "exists"
            cryptokey_id: "{{ last_id }}"
          ignore_errors: true
          register: result_get
    - ansible.builtin.assert:
        quiet: true
        that:
          - result_active['exception'] is not defined
          - result_get['exception'] is not defined
          - not result_active.failed
          - not result_get.failed
          - result_get.cryptokey.active == true
          - output["algorithm"] == 15
      vars:
        output: "{{ lookup('dig_local', 'cryptokeys.example.', qtype='DNSKEY', flat=0, fail_on_error=false, real_empty=false) }}"

    - name: check operation on non-existent zone
      kpfleming.powerdns_auth.cryptokey:
        apikey: foo
        zone_name: non-existatnt.example.
        state: exists
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is defined
          - result.failed

    - name: check imported key with wrong parameters
      kpfleming.powerdns_auth.cryptokey:
        <<: *common
        state: present
        cryptokey:
          keytype: zsk
          dnskey: "257 3 15 lMu/7quhLeSueMcdlt3T0sxln32yhrhASCKKDB1xJOk="
          active: true
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is defined
          - result.failed

    - name: check imported key with wrong parameters
      kpfleming.powerdns_auth.cryptokey:
        <<: *common
        state: present
        cryptokey:
          algorithm: ed25519
          active: true
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is defined
          - result.failed

    - name: check non-existent key deletion
      kpfleming.powerdns_auth.cryptokey:
        <<: *common
        state: absent
        cryptokey_id: 100
      ignore_errors: true
      register: result
    - ansible.builtin.assert:
        quiet: true
        that:
          - result['exception'] is defined
          - result.failed
