---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - rrset-vars.yml

  vars:
    ansible_python_interpreter: python
    pdns_version: "{{ lookup('ansible.builtin.env', 'pdns_version') }}"
    api_key: foo

  pre_tasks:
    - name: Creating template for all rrset types
      ansible.builtin.template:
        src: /template/all-rrset-types.yml.j2
        dest: ./test-rrset-all-types.yml

  tasks:
    - name: creating each type of supported DNS record
      ansible.builtin.include_tasks:
        file: test-rrset-all-types.yml
